version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    depends_on:
      - nest-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  nest-app:
    build: .
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: project_database
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_database
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
